#' @name uiAbout
#' @title uiAbout
#' @description Builds the UI of the about context.
#' @param id Namespace identifier.
#' @return HTML source code.
#' @export
uiAbout <- function(id = "about") {
  cat("uiAbout\n")
  ns <- NS(id)
  
  tabItem(tabName = "about",
          fluidRow(box(title = "About",
                       solidHeader = TRUE,
                       status = "primary",
                       width = 12,
                       img(src = './img/logo.jpeg', alt = "logo"),
                       h2("Info"),
                       p(paste("rrisk is is a set of functions running in the", 
                               "distributed rrisk-workspace using the", 
                               "R software package (R Development Core Team", 
                               "(2007). R: A Language and Environment for", 
                               "Statistical Computing, R Foundation for", 
                               "Statistical Computing, Vienna, Austria,", 
                               "ISBN 3-900051-07-0, http://www.R-project.org)."), 
                         class = "text-justify"),
                       h2("Copyright"),
                       p("Copyright 2009 [under open source GNU licensing agreement of R].", 
                         class = "margin-bottom-none"),
                       p("Federal Institute for Risk Assessment (BfR), Germany."),
                       h2("Contact"),
                       p("Matthias Greiner <matthias.greiner@bfr.bund.de>", 
                         class = "margin-bottom-none"),
                       p("https://www.bfr.bund.de/cd/52162"),
                       h2("Authors"),
                       p("Matthias Greiner (BfR)", 
                         class = "margin-bottom-none"),
                       p("Robert Opitz (BfR)", 
                         class = "margin-bottom-none"),
                       p("Christin Wallstab (BfR)", 
                         class = "margin-bottom-none"),
                       p("Thomas Selhorst (BfR)", 
                         class = "margin-bottom-none"),
                       p("Christine M\u00FCller-Graf (BfR)", 
                         class = "margin-bottom-none"),
                       br(),
                       p("Clemens Wickboldt (MaibornWolff GmbH)", 
                         class = "margin-bottom-none"),
                       p("Ren\u00E9 M\u00FCller (MaibornWolff GmbH)", 
                         class = "margin-bottom-none"),
                       p("Nils Effinghausen (MaibornWolff GmbH)", 
                         class = "margin-bottom-none"),
                       h2("Notes"),
                       p(paste("rrisk is a project under development.", 
                               "Contributions are welcome!")),
                       h2("Disclaimer"),
                       p(paste("THE rrisk SOFTWARE IS PROVIDED BY THE", 
                               "COPYRIGHT HOLDERS AND CONTRIBUTORS 'AS IS'", 
                               "AND ANY EXPRESS OR IMPLIED WARRANTIES,", 
                               "INCLUDING, BUT NOT LIMITED TO, THE IMPLIED", 
                               "WARRANTIES OF MERCHANTABILITY AND FITNESS FOR", 
                               "A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO", 
                               "EVENT SHALL THE COPYRIGHT OWNER OR", 
                               "CONTRIBUTORS BE LIABLE FOR ANY DIRECT,", 
                               "INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR", 
                               "CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT", 
                               "LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS", 
                               "OR SERVICES; LOSS OF USE, DATA, OR PROFITS;", 
                               "OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND", 
                               "ON ANY THEORY OF LIABILITY, WHETHER IN", 
                               "CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING", 
                               "NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY", 
                               "OUT OF THE USE OF THIS SOFTWARE, EVEN IF", 
                               "ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.")),
                       h2("Version"),
                       p("rrisk version 0.1.0 <2021-10-06>"),
                       h2("User Guide"),
                       p("User guide for rrisk 2.12.0 console version!"),
                       a(href     = "pdf/user-guide.pdf", 
                         "Download user guide", 
                         download = NA, 
                         target   = "_blank"))))
}
