#' @name uiSetup
#' @title uiSetup
#' @description Builds the UI of the dashboard context.
#' @param id Namespace identifier.
#' @return HTML source code.
#' @export
uiSetup <- function(id = "setup") {
  cat("uiSetup\n")
  ns <- NS(id)
  
  tabItem(tabName = "setup",
          fluidRow(box(title       = "Create new model",
                       solidHeader = TRUE,
                       status      = "primary",
                       width       = 4,
                       textInput(inputId     = ns("txbModelName"),
                                 label       = "",
                                 value       = "",
                                 placeholder = "Model name"),
                       actionButton(inputId = ns("btnCreateModel"),
                                    class   = "center-full-width",
                                    label   = "Create")),
                   box(title       = "Active model",
                       solidHeader = TRUE,
                       status      = "primary",
                       width       = 4,
                       class       = "flex-center",
                       verbatimTextOutput(outputId  = ns("labActiveModelName"),
                                          placeholder = TRUE)),
                   box(title       = "Report",
                       solidHeader = TRUE,
                       status      = "primary",
                       width       = 4,
                       class       = "flex-center",
                       div(class = "center-full-width",
                           downloadButton(outputId = ns("btnExportReportZip"),
                                          label    = "Export (zip)",
                                          icon     = icon("save")),
                           downloadButton(outputId = ns("btnExportReportPdf"),
                                          label    = "Export Report",
                                          icon     = icon("save"))))),
          fluidRow(box(title       = "Load / save model",
                       solidHeader = TRUE,
                       status      = "primary",
                       width       = 12,
                       fileInput(inputId     = ns("filModelFile"),
                                 label       = "Load a model:",
                                 multiple    = FALSE,
                                 accept      = c(".rdata", ".rda"),
                                 buttonLabel = "Browse...",
                                 placeholder = "select file"),
                       hr(),
                       strong("Load an example:"),
                       br(),
                       actionButton(inputId = ns("btnExamplePerfringensLee"),
                                    label   = "C. perfringens in processed cheese",
                                    class   = "center-full-width",
                                    icon    = icon("gift")),
                       br(), br(),
                       actionButton(inputId = ns("btnExampleEcoliPouillot"),
                                    label   = "Ecoli-Pouillot",
                                    class   = "center-full-width",
                                    icon    = icon("gift")),
                       hr(),
                       strong("Save the active model:"),
                       br(),
                       downloadButton(outputId = ns("btnModelSave"),
                                      label    = "Save Model (rda)",
                                      class    = "center-full-width",
                                      icon     = icon("save")),
                       br(), br(),
                       downloadButton(outputId = ns("btnJsonExport"),
                                      label    = "Export Model (json)",
                                      class    = "center-full-width",
                                      icon     = icon("save")))))
}
